version: "3.8"

services:
  ubuntu:
    build:
      context: .
      dockerfile: Dockerfile.ubuntu
    container_name: test-ubuntu
    tty: true

  arch:
    build:
      context: .
      dockerfile: Dockerfile.arch
    container_name: test-arch
    tty: true

  alpine:
    build:
      context: .
      dockerfile: Dockerfile.alpine
    container_name: test-alpine
    tty: true

  windows:
    build:
      context: .
      dockerfile: Dockerfile.windows
    container_name: test-windows
    tty: true
