FROM ubuntu:latest

RUN apt update && apt install -y curl git

WORKDIR /root
RUN curl -fsSL https://raw.githubusercontent.com/thenameiswiiwin/.dotfiles/main/resources/setup | bash

CMD ["/bin/bash"]

