FROM mcr.microsoft.com/windows/server:ltsc2022
SHELL ["powershell", "-Command"]
RUN Write-Host "Windows container setup"
COPY entrypoint.ps1 C:/entrypoint.ps1
CMD ["powershell.exe", "C:/entrypoint.ps1"]
