version: "3.8"

services:
  ubuntu:
    build:
      context: .
      dockerfile: Dockerfile.ubuntu
    container_name: test-ubuntu
    tty: true
    platform: linux/amd64

  arch:
    build:
      context: .
      dockerfile: Dockerfile.arch
    container_name: test-arch
    tty: true
    platform: linux/amd64

  alpine:
    build:
      context: .
      dockerfile: Dockerfile.alpine
    container_name: test-alpine
    tty: true
    platform: linux/amd64

  windows:
    build:
      context: .
      dockerfile: Dockerfile.windows
    container_name: test-windows
    tty: true
    platform: windows/amd64
    deploy:
      replicas: 0 # Prevents deployment on macOS/Linux

